In [7]:
%pip install scikit-learn

import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score # type: ignore

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.6.1)




[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
parkinsons_dataset = pd.read_csv("../Datasets/parkinsons.csv")

In [17]:
parkinsons_dataset.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [18]:
parkinsons_dataset.describe()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count   195.000000    195.000000    195.000000      195.000000   
mean    154.228641    197.104918    116.324631        0.006220   
std      41.390065     91.491548     43.521413        0.004848   
min      88.333000    102.145000     65.476000        0.001680   
25%     117.572000    134.862500     84.291000        0.003460   
50%     148.790000    175.829000    104.315000        0.004940   
75%     182.769000    224.205500    140.018500        0.007365   
max     260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  ...  Shimmer:DDA         NHR         HNR      status  \
count        195.000000  ...   195.000000  195.000000  195.000000  195.000000   
mean           0.282251  ...     0.046993    0.024847   21.885974    0.753846   
std            0.194877  ...     0.030459    0.040418    4.425764    0.431878   
min            0.085000  ...     0.013640    0.000650    8.441000    0.000000   
25%            0.148500  ...     0.024735    0.005925   19.198000    1.000000   
50%            0.221000  ...     0.038360    0.011660   22.085000    1.000000   
75%            0.350000  ...     0.060795    0.025640   25.075500    1.000000   
max            1.302000  ...     0.169420    0.314820   33.047000    1.000000   

             RPDE         DFA     spread1     spread2          D2         PPE  
count  195.000000  195.000000  195.000000  195.000000  195.000000  195.000000  
mean     0.498536    0.718099   -5.684397    0.226510    2.381826    0.206552  
std      0.103942    0.055336    1.090208    0.083406    0.382799    0.090119  
min      0.256570    0.574282   -7.964984    0.006274    1.423287    0.044539  
25%      0.421306    0.674758   -6.450096    0.174351    2.099125    0.137451  
50%      0.495954    0.722254   -5.720868    0.218885    2.361532    0.194052  
75%      0.587562    0.761881   -5.046192    0.279234    2.636456    0.252980  
max      0.685151    0.825288   -2.434031    0.450493    3.671155    0.527367  

[8 rows x 23 columns]

In [19]:
parkinsons_dataset.shape

(195, 24)

In [21]:
parkinsons_dataset['status']

0      1
1      1
2      1
3      1
4      1
      ..
190    0
191    0
192    0
193    0
194    0
Name: status, Length: 195, dtype: int64

In [22]:
#getting more informations about the dataset
parkinsons_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [23]:
# checking for missing values in each column
parkinsons_dataset.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [24]:
# distribution of target variable
parkinsons_dataset['status'].value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [25]:
# here the data is very unbalanced as the people having disease are 147 so the data needs to be balanced for unbiased prediction. 

In [26]:
# grouping the data based on target variable, excluding the 'name' column
#parkinsons_dataset.groupby('status').mean() it shows error :
#The error occurs because the name column in the dataframe is of type object, and the mean() function cannot be applied to it. To fix this, you need to exclude the name column when calculating the mean.

parkinsons_dataset.drop(columns=['name']).groupby('status').mean()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
status                                                            
0        181.937771    223.636750    145.207292        0.003866   
1        145.180762    188.441463    106.893558        0.006989   

        MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
status                                                                   
0               0.000023  0.001925  0.002056    0.005776      0.017615   
1               0.000051  0.003757  0.003900    0.011273      0.033658   

        MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA       NHR        HNR  \
status                    ...                                               
0               0.162958  ...  0.013305     0.028511  0.011483  24.678750   
1               0.321204  ...  0.027600     0.053027  0.029211  20.974048   

            RPDE       DFA   spread1   spread2        D2       PPE  
status                                                              
0       0.442552  0.695716 -6.759264  0.160292  2.154491  0.123017  
1       0.516816  0.725408 -5.333420  0.248133  2.456058  0.233828  

[2 rows x 22 columns]

#  Data Pre-Processing

# separating the features and target

In [27]:
x = parkinsons_dataset.drop(columns=['name', 'status'], axis=1)
y = parkinsons_dataset['status']

In [28]:
x.head()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  MDVP:Jitter(Abs)  \
0      119.992       157.302        74.997         0.00784           0.00007   
1      122.400       148.650       113.819         0.00968           0.00008   
2      116.682       131.111       111.555         0.01050           0.00009   
3      116.676       137.871       111.366         0.00997           0.00009   
4      116.014       141.781       110.655         0.01284           0.00011   

   MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  MDVP:Shimmer(dB)  ...  \
0   0.00370   0.00554     0.01109       0.04374             0.426  ...   
1   0.00465   0.00696     0.01394       0.06134             0.626  ...   
2   0.00544   0.00781     0.01633       0.05233             0.482  ...   
3   0.00502   0.00698     0.01505       0.05492             0.517  ...   
4   0.00655   0.00908     0.01966       0.06425             0.584  ...   

   MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE       DFA   spread1  \
0   0.02971      0.06545  0.02211  21.033  0.414783  0.815285 -4.813031   
1   0.04368      0.09403  0.01929  19.085  0.458359  0.819521 -4.075192   
2   0.03590      0.08270  0.01309  20.651  0.429895  0.825288 -4.443179   
3   0.03772      0.08771  0.01353  20.644  0.434969  0.819235 -4.117501   
4   0.04465      0.10470  0.01767  19.649  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 22 columns]

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42) 

In [30]:
X_train.shape, X_test.shape

((156, 22), (39, 22))

In [31]:
X_train.head()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
5        120.552       131.162       113.787         0.00968   
135      110.453       127.611       105.554         0.00494   
122      138.190       203.522        83.340         0.00704   
167      260.105       264.919       237.303         0.00339   
85       180.978       200.125       155.495         0.00406   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
5             0.00008   0.00463   0.00750     0.01388       0.04701   
135           0.00004   0.00244   0.00315     0.00731       0.04128   
122           0.00005   0.00406   0.00398     0.01218       0.04479   
167           0.00001   0.00205   0.00186     0.00616       0.02030   
85            0.00002   0.00220   0.00244     0.00659       0.03852   

     MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE  \
5               0.456  ...   0.03243      0.06985  0.01222  21.378  0.415564   
135             0.379  ...   0.03316      0.06688  0.02529  17.707  0.653427   
122             0.441  ...   0.03220      0.07761  0.01968  18.305  0.538016   
167             0.197  ...   0.01367      0.03557  0.00910  21.083  0.440988   
85              0.331  ...   0.02877      0.06321  0.02782  16.176  0.583574   

          DFA   spread1   spread2        D2       PPE  
5    0.825069 -4.242867  0.299111  2.187560  0.357775  
135  0.706687 -5.333619  0.322044  2.631793  0.228319  
122  0.741480 -5.418787  0.160267  2.090438  0.229892  
167  0.628058 -7.517934  0.160414  1.881767  0.075587  
85   0.727747 -5.657899  0.315903  3.098256  0.200423  

[5 rows x 22 columns]

In [32]:
model = svm.SVC(kernel='linear')

In [33]:
model.fit(X_train,Y_train)

SVC(kernel='linear')

In [34]:
# make predictions
y_pred = model.predict(X_test)

In [35]:
print(accuracy_score(Y_test,y_pred))

0.8717948717948718


In [36]:
# compute confusion matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(Y_test, y_pred)

In [37]:
# print results
print("confusion_matrix : ")
print(conf_matrix)


confusion_matrix : 
[[ 3  4]
 [ 1 31]]


In [38]:
from sklearn.metrics import classification_report
print("\nclassification_report : ")
print(classification_report(Y_test, y_pred))


classification_report : 
              precision    recall  f1-score   support

           0       0.75      0.43      0.55         7
           1       0.89      0.97      0.93        32

    accuracy                           0.87        39
   macro avg       0.82      0.70      0.74        39
weighted avg       0.86      0.87      0.86        39



In [ ]:
# here the data is moderately imbalanced(75%+ve & 25%-ve) the precision will be very high and recall will be very low.
# this means it is very accurate when predicting +ves , but it fails to detect many actual +ves(high false -ves) 

## DATA CLEANING FOR IMBALANCED DATA ( UNDERSAMPLING)

# TOMEK'S LINK

In [39]:
%pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [40]:
from imblearn.under_sampling import TomekLinks

# Separate features and target
X = parkinsons_dataset.drop(columns=['name', 'status'], axis=1)
y = parkinsons_dataset['status']

# Apply Tomek's Link
tl = TomekLinks()
X_res, y_res = tl.fit_resample(X, y)

# Check the shape of the resampled data
print("Original dataset shape:", X.shape, y.shape)
print("Resampled dataset shape:", X_res.shape, y_res.shape)

Original dataset shape: (195, 22) (195,)
Resampled dataset shape: (189, 22) (189,)


In [41]:
# Split the resampled data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

In [42]:
# Train the model
model = svm.SVC(kernel='linear')
model.fit(X_train, Y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(Y_test, y_pred))

Accuracy: 0.8947368421052632


In [43]:
# print results
print("confusion_matrix : ")
print(conf_matrix)


confusion_matrix : 
[[ 3  4]
 [ 1 31]]


In [44]:
print("\nclassification_report : ")
print(classification_report(Y_test, y_pred))


classification_report : 
              precision    recall  f1-score   support

           0       1.00      0.64      0.78        11
           1       0.87      1.00      0.93        27

    accuracy                           0.89        38
   macro avg       0.94      0.82      0.85        38
weighted avg       0.91      0.89      0.89        38



In [45]:

from sklearn.metrics import f1_score

f1 = f1_score(Y_test, y_pred)

print("F1 Score: ", f1)

F1 Score:  0.9310344827586207


In [32]:
import pickle
filename = 'parkinsons_model.sav'
pickle.dump(model, open(filename, 'wb')) ##wb = write byte

In [48]:
%pip install scikit-learn

from sklearn.linear_model import LogisticRegression

# Train the Logistic Regression model
logistic_model = LogisticRegression(max_iter=2000)
logistic_model.fit(X_train, Y_train)


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


LogisticRegression(max_iter=2000)

In [49]:
# Make predictions
y_pred = model.predict(X_test)

In [50]:
# Evaluate the model
accuracy = accuracy_score(Y_test, y_pred)
conf_matrix = confusion_matrix(Y_test, y_pred)
class_report = classification_report(Y_test, y_pred)
f1 = f1_score(Y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
print("F1 Score:", f1)

Accuracy: 0.8947368421052632
Confusion Matrix:
 [[ 7  4]
 [ 0 27]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.64      0.78        11
           1       0.87      1.00      0.93        27

    accuracy                           0.89        38
   macro avg       0.94      0.82      0.85        38
weighted avg       0.91      0.89      0.89        38

F1 Score: 0.9310344827586207


In [51]:
from sklearn.tree import DecisionTreeClassifier

In [52]:
# Train the Decision Tree model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [53]:
# Make predictions
y_pred = model.predict(X_test)

In [54]:
# Evaluate the model
accuracy = accuracy_score(Y_test, y_pred)
conf_matrix = confusion_matrix(Y_test, y_pred)
class_report = classification_report(Y_test, y_pred)
f1 = f1_score(Y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
print("F1 Score:", f1)

Accuracy: 0.8947368421052632
Confusion Matrix:
 [[ 7  4]
 [ 0 27]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.64      0.78        11
           1       0.87      1.00      0.93        27

    accuracy                           0.89        38
   macro avg       0.94      0.82      0.85        38
weighted avg       0.91      0.89      0.89        38

F1 Score: 0.9310344827586207


In [61]:
# Save the model to a file
filename = 'parkinsons_decision_tree_model.sav'
pickle.dump(model, open(filename, 'wb'))  # wb = write byte

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
# Train the Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [57]:
# Make predictions
y_pred = model.predict(X_test)

In [58]:
# Evaluate the model
accuracy = accuracy_score(Y_test, y_pred)
conf_matrix = confusion_matrix(Y_test, y_pred)
class_report = classification_report(Y_test, y_pred)
f1 = f1_score(Y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
print("F1 Score:", f1)

Accuracy: 0.9210526315789473
Confusion Matrix:
 [[ 8  3]
 [ 0 27]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.73      0.84        11
           1       0.90      1.00      0.95        27

    accuracy                           0.92        38
   macro avg       0.95      0.86      0.89        38
weighted avg       0.93      0.92      0.92        38

F1 Score: 0.9473684210526315


In [60]:
import pickle
# Save the model to a file
filename = 'parkinsons_random_forest_model.sav'
pickle.dump(model, open(filename, 'wb'))  # wb = write byte